blank_issues_enabled: true
contact_links:
  - name: camenduru's Discord Server
    url: https://discord.gg/k5BwmmvJJU
    about: Join the discord server for more help from the community
version https://git-lfs.github.com/spec/v1
